"use client";

import { useEffect, useRef, useState } from "react";

/**
 * Depth-map parallax hover — the trionn.com/about lion head interaction,
 * reverse-engineered from their shipped bundle and ported faithfully.
 *
 * HOW THEIRS ACTUALLY WORKS (extracted from their production chunk): the
 * lion is NOT a 3D model and NOT sliced strips. It is a fullscreen WebGL
 * quad sampling two textures — the photo (`uImage`) and a heavily blurred
 * grayscale depth map (`uDepth`, white = near, black = far). Each pixel is
 * displaced by `mouse * depth * amount`, so the beak (near) travels
 * further than the neck (far) and the background not at all. That depth
 * gradient across one continuous image is the entire "head turns to follow
 * you" illusion. Their numbers, kept verbatim here: mouse eased 0.07/frame,
 * displacement 0.03–0.042 UV modulated by a ~5s "breathing" sine so the
 * head drifts while idle, chromatic aberration on R/B at ±0.16 of the
 * displacement, DPR capped at 2 (1.5 mobile), rAF paused off-screen.
 *
 * Departures from theirs, deliberate: the background is a uniform prop
 * (their white canvas becomes our cream), sizing follows the host box
 * (their 1.8×-viewport canvas is specific to their full-bleed layout), and
 * cursor-leaving-the-window recentres via `pointerout` (their
 * window-level `mouseleave` never fires in Chromium — silent no-op).
 *
 * The depth maps live next to the images (eagle-front-depth.jpg) and are
 * generated by scratchpad/gen_depth.py: Depth-Anything-V2-small → mask the
 * flat background to black → gaussian blur at width/55. The blur is
 * load-bearing: sharp depth edges displace neighbouring pixels apart and
 * tear the image; blurred depth moves the head as one cohesive mass.
 *
 * Falls back to a plain <img> when WebGL is unavailable or the user
 * prefers reduced motion.
 */

const VERT = `
attribute vec2 aPosition;
varying vec2 vUv;
void main() {
  vUv = aPosition * 0.5 + 0.5;
  gl_Position = vec4(aPosition, 0.0, 1.0);
}`;

const FRAG = `
precision highp float;
varying vec2 vUv;
uniform vec2 uResolution;
uniform sampler2D uImage;
uniform sampler2D uDepth;
uniform vec2 uImageScale;
uniform vec2 uMouseEase;
uniform float uAmount;
uniform float uHover;
uniform vec3 uBg;

vec2 containUv(vec2 uv, vec2 viewport, vec2 image) {
  float vr = viewport.x / viewport.y;
  float ir = image.x / image.y;
  vec2 scale = vec2(1.0);
  if (vr > ir) scale.x = ir / vr; else scale.y = vr / ir;
  return (uv - 0.5) / scale + 0.5;
}

void main() {
  vec2 contained = containUv(vUv, uResolution, uImageScale);
  bool outside = contained.x < 0.0 || contained.x > 1.0 || contained.y < 0.0 || contained.y > 1.0;
  if (outside) { gl_FragColor = vec4(uBg, 1.0); return; }
  vec2 mouse = (uMouseEase - 0.5) * vec2(2.0, -2.0);
  float depth = texture2D(uDepth, contained).r;
  vec2 disp = mouse * depth * (uAmount * uHover);
  vec2 uv = contained - disp;
  float r = texture2D(uImage, uv + disp * 0.16).r;
  float g = texture2D(uImage, uv).g;
  float b = texture2D(uImage, uv - disp * 0.16).b;
  float a = texture2D(uImage, uv).a;
  vec3 color = mix(uBg, vec3(r, g, b), a);
  gl_FragColor = vec4(color, 1.0);
}`;

function hexToRgb(hex: string): [number, number, number] {
  const n = parseInt(hex.replace("#", ""), 16);
  return [((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255];
}

export default function DepthParallax({
  src,
  depthSrc,
  bg = "#fff3d3",
  strength = 1,
  className = "",
  ariaLabel,
}: {
  src: string;
  /** grayscale depth map, same framing as src — white near, black far */
  depthSrc: string;
  /** canvas letterbox + matte color; must match the section background */
  bg?: string;
  /** multiplier on trionn's 0.03–0.042 UV displacement */
  strength?: number;
  className?: string;
  ariaLabel?: string;
}) {
  const hostRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [fallback, setFallback] = useState(false);

  useEffect(() => {
    const canvas = canvasRef.current;
    const host = hostRef.current;
    if (!canvas || !host) return;

    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
      setFallback(true);
      return;
    }
    const mobile = window.innerWidth <= 768;
    const gl = canvas.getContext("webgl", {
      antialias: !mobile,
      alpha: true,
      premultipliedAlpha: false,
      powerPreference: "high-performance",
    });
    if (!gl) {
      setFallback(true);
      return;
    }

    let dead = false;
    let texImage: WebGLTexture | null = null;
    let texDepth: WebGLTexture | null = null;
    const compile = (type: number, source: string) => {
      const sh = gl.createShader(type)!;
      gl.shaderSource(sh, source);
      gl.compileShader(sh);
      if (!gl.getShaderParameter(sh, gl.COMPILE_STATUS)) {
        console.error("DepthParallax shader:", gl.getShaderInfoLog(sh));
        return null;
      }
      return sh;
    };
    const vs = compile(gl.VERTEX_SHADER, VERT);
    const fs = compile(gl.FRAGMENT_SHADER, FRAG);
    if (!vs || !fs) {
      setFallback(true);
      return;
    }
    const prog = gl.createProgram()!;
    gl.attachShader(prog, vs);
    gl.attachShader(prog, fs);
    gl.linkProgram(prog);
    if (!gl.getProgramParameter(prog, gl.LINK_STATUS)) {
      console.error("DepthParallax link:", gl.getProgramInfoLog(prog));
      setFallback(true);
      return;
    }
    gl.useProgram(prog);

    const buf = gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER, buf);
    gl.bufferData(
      gl.ARRAY_BUFFER,
      new Float32Array([-1, -1, 1, -1, -1, 1, -1, 1, 1, -1, 1, 1]),
      gl.STATIC_DRAW
    );
    const aPos = gl.getAttribLocation(prog, "aPosition");
    gl.enableVertexAttribArray(aPos);
    gl.vertexAttribPointer(aPos, 2, gl.FLOAT, false, 0, 0);

    const U = {
      resolution: gl.getUniformLocation(prog, "uResolution"),
      image: gl.getUniformLocation(prog, "uImage"),
      depth: gl.getUniformLocation(prog, "uDepth"),
      imageScale: gl.getUniformLocation(prog, "uImageScale"),
      mouseEase: gl.getUniformLocation(prog, "uMouseEase"),
      amount: gl.getUniformLocation(prog, "uAmount"),
      hover: gl.getUniformLocation(prog, "uHover"),
      bg: gl.getUniformLocation(prog, "uBg"),
    };
    gl.uniform3f(U.bg, ...hexToRgb(bg));

    // trionn's state object, verbatim shape: raw mouse in [0,1] canvas
    // space, eased copy lerped 7% per frame, hover fixed at 1
    const st = {
      mouse: { x: 0.5, y: 0.5 },
      eased: { x: 0.5, y: 0.5 },
      hover: 1,
    };
    let ready = false;
    let raf = 0;
    let running = false;
    let visible = true;

    const makeTexture = (image: TexImageSource) => {
      const t = gl.createTexture();
      gl.bindTexture(gl.TEXTURE_2D, t);
      // DOM images upload top-row-first but GL UVs run bottom-up — without
      // this flip the eagle renders upside-down
      gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true);
      // NPOT textures in WebGL1: clamp + linear, no mipmaps (their setup)
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
      gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, image);
      return t;
    };
    const load = (url: string) =>
      new Promise<HTMLImageElement>((res, rej) => {
        const im = new Image();
        im.onload = () => (im.decode ? im.decode().then(() => res(im)).catch(() => res(im)) : res(im));
        im.onerror = rej;
        im.src = url;
      });

    const drawNow = (now: number) => {
      // trionn's ~5s breathing sine, computed CPU-side: feeding raw
      // performance.now() into the shader flickers on GPUs that silently
      // demote highp to mediump (the large float loses sin() precision)
      const breathing = Math.sin(now * 0.0012) * 0.5 + 0.5;
      gl.uniform2f(U.resolution, canvas.width, canvas.height);
      gl.uniform2f(U.mouseEase, st.eased.x, st.eased.y);
      gl.uniform1f(U.amount, (0.03 + 0.012 * breathing) * strength);
      gl.uniform1f(U.hover, st.hover);
      gl.drawArrays(gl.TRIANGLES, 0, 6);
    };
    const frame = (now: number) => {
      st.eased.x += (st.mouse.x - st.eased.x) * 0.07;
      st.eased.y += (st.mouse.y - st.eased.y) * 0.07;
      drawNow(now);
      raf = requestAnimationFrame(frame);
    };
    const setRunning = (on: boolean) => {
      if (on && !running && ready) {
        running = true;
        raf = requestAnimationFrame(frame);
      } else if (!on && running) {
        running = false;
        cancelAnimationFrame(raf);
      }
    };

    const resize = () => {
      const r = host.getBoundingClientRect();
      const dpr = Math.min(window.devicePixelRatio || 1, mobile ? 1.5 : 2);
      const w = Math.max(1, Math.round(r.width * dpr));
      const h = Math.max(1, Math.round(r.height * dpr));
      if (canvas.width !== w || canvas.height !== h) {
        canvas.width = w;
        canvas.height = h;
        gl.viewport(0, 0, w, h);
        // setting width/height wipes the buffer — repaint in the same task
        // or the canvas shows a blank frame every resize (mobile URL bar,
        // window drags), which reads as flicker
        if (ready) drawNow(performance.now());
      }
    };
    const ro = new ResizeObserver(resize);
    ro.observe(host);
    resize();

    // trionn tracks the cursor WINDOW-wide, normalized + clamped to the
    // canvas box — the head watches you across the whole page, not only
    // while hovering it. mouse-leaves-window recentres (eased, so the
    // head "settles back" rather than snapping).
    const point = (cx: number, cy: number) => {
      const r = canvas.getBoundingClientRect();
      if (!r.width || !r.height) return;
      st.mouse.x = Math.max(0, Math.min(1, (cx - r.left) / r.width));
      st.mouse.y = Math.max(0, Math.min(1, (cy - r.top) / r.height));
      st.hover = 1;
    };
    const onMove = (e: MouseEvent) => point(e.clientX, e.clientY);
    const onTouch = (e: TouchEvent) => {
      if (e.touches.length) point(e.touches[0].clientX, e.touches[0].clientY);
    };
    const onOut = (e: PointerEvent) => {
      if (e.relatedTarget === null) {
        st.mouse.x = 0.5;
        st.mouse.y = 0.5;
      }
    };
    window.addEventListener("mousemove", onMove);
    window.addEventListener("touchmove", onTouch, { passive: true });
    window.addEventListener("touchstart", onTouch, { passive: true });
    window.addEventListener("pointerout", onOut);

    // flaky GPUs (VRAM pressure, driver resets) can drop the context —
    // without this the eagle strobes or goes permanently blank; the plain
    // <img> fallback is invisible to everyone else
    const onLost = (e: Event) => {
      e.preventDefault();
      setFallback(true);
    };
    canvas.addEventListener("webglcontextlost", onLost);

    const io = new IntersectionObserver(
      ([entry]) => {
        visible = entry.isIntersecting;
        setRunning(visible);
      },
      { threshold: 0, rootMargin: "64px 0px" }
    );
    io.observe(host);

    Promise.all([load(src), load(depthSrc)])
      .then(([img, dep]) => {
        if (dead) return;
        texImage = makeTexture(img);
        texDepth = makeTexture(dep);
        gl.activeTexture(gl.TEXTURE0);
        gl.bindTexture(gl.TEXTURE_2D, texImage);
        gl.uniform1i(U.image, 0);
        gl.activeTexture(gl.TEXTURE1);
        gl.bindTexture(gl.TEXTURE_2D, texDepth);
        gl.uniform1i(U.depth, 1);
        gl.uniform2f(U.imageScale, img.naturalWidth, img.naturalHeight);
        ready = true;
        canvas.dataset.ready = "1";
        setRunning(visible);
      })
      .catch(() => setFallback(true));

    // debug hook — inspectable state, no behavioural effect
    (host as HTMLDivElement & { __depth?: typeof st }).__depth = st;

    return () => {
      dead = true;
      canvas.removeEventListener("webglcontextlost", onLost);
      window.removeEventListener("mousemove", onMove);
      window.removeEventListener("touchmove", onTouch);
      window.removeEventListener("touchstart", onTouch);
      window.removeEventListener("pointerout", onOut);
      ro.disconnect();
      io.disconnect();
      cancelAnimationFrame(raf);
      if (texImage) gl.deleteTexture(texImage);
      if (texDepth) gl.deleteTexture(texDepth);
      gl.deleteProgram(prog);
      gl.deleteShader(vs);
      gl.deleteShader(fs);
      gl.deleteBuffer(buf);
      gl.getExtension("WEBGL_lose_context")?.loseContext();
    };
  }, [src, depthSrc, bg, strength]);

  return (
    <div
      ref={hostRef}
      role={ariaLabel ? "img" : undefined}
      aria-label={ariaLabel}
      className={`relative [touch-action:pan-y] ${className}`}
    >
      {fallback ? (
        // eslint-disable-next-line @next/next/no-img-element
        <img src={src} alt="" className="absolute inset-0 size-full object-contain" />
      ) : (
        <canvas ref={canvasRef} className="absolute inset-0 size-full" />
      )}
    </div>
  );
}
